<a href="https://colab.research.google.com/github/hamza36-ui/task2/blob/main/Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [3]:
import numpy as np

print("NumPy version:", np.__version__)

np.show_config()

NumPy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [4]:
import numpy as np

numeric_list = [1, 2, 3, 4, 5]

array_1d = np.array(numeric_list)

print("1D NumPy array:", array_1d)

1D NumPy array: [1 2 3 4 5]


#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [5]:
import numpy as np

null_vector = np.zeros(9)

print("Null vector of size 9:", null_vector)

Null vector of size 9: [0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Memory size of the array:", arr.nbytes, "bytes")

Memory size of the array: 40 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [7]:
import numpy as np

help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [8]:
import numpy as np

vector = np.zeros(12)

vector[5] = 1

print("Null vector with 1 at the sixth position:\n", vector)

Null vector with 1 at the sixth position:
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [9]:
import numpy as np

vector = np.arange(20, 60)

print("Vector with values from 20 to 59:")
print(vector)

Vector with values from 20 to 59:
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [10]:
import numpy as np

vector = np.array([10, 20, 30, 40, 50])

reversed_vector = vector[::-1]

print("Original vector:", vector)
print("Reversed vector:", reversed_vector)

Original vector: [10 20 30 40 50]
Reversed vector: [50 40 30 20 10]


#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [11]:
import numpy as np

values = np.arange(12, 21)

matrix = values.reshape(3, 3)

print("3x3 matrix with values from 12 to 20:")
print(matrix)

3x3 matrix with values from 12 to 20:
[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [12]:
import numpy as np

arr = np.array([3, 7, 0, 0, 9, 0])

indices = np.nonzero(arr)

print("Indices of non-zero elements:", indices[0])

Indices of non-zero elements: [0 1 4]


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [13]:
import numpy as np

identity_matrix = np.eye(4)

print("4x4 Identity matrix:")
print(identity_matrix)

4x4 Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [14]:
import numpy as np

random_array = np.random.rand(2, 2, 2)

print("2x2x2 array with random values:")
print(random_array)

2x2x2 array with random values:
[[[0.72220561 0.63255167]
  [0.15626341 0.10931541]]

 [[0.79244991 0.07226894]
  [0.23337183 0.71664857]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [15]:
import numpy as np

array_9x9 = np.random.rand(9, 9)

min_val = array_9x9.min()
max_val = array_9x9.max()

print("9x9 array with random values:")
print(array_9x9)
print(f"\nMinimum value: {min_val}")
print(f"Maximum value: {max_val}")

9x9 array with random values:
[[0.72827467 0.96989222 0.93190659 0.49114283 0.66894177 0.12871166
  0.12020559 0.23048258 0.747593  ]
 [0.86866712 0.68372968 0.32720218 0.19188033 0.22261025 0.52416266
  0.65237899 0.54425238 0.57447258]
 [0.07524799 0.23928475 0.70099839 0.37634265 0.12017257 0.06143913
  0.88954787 0.41164282 0.60849017]
 [0.29489409 0.22808242 0.2150358  0.16702559 0.23058849 0.30558909
  0.30058895 0.71837742 0.05767021]
 [0.74328585 0.62718353 0.00304411 0.79520684 0.55846737 0.45384981
  0.92193494 0.10291135 0.0620345 ]
 [0.093994   0.63479416 0.3695265  0.22930488 0.36692517 0.2498921
  0.95954617 0.3046532  0.80963969]
 [0.21893915 0.65158441 0.96183891 0.5458719  0.86410378 0.67089494
  0.70047121 0.24416194 0.82389815]
 [0.72625039 0.87478241 0.26626139 0.91139402 0.4942128  0.99087935
  0.65472194 0.4967254  0.61570665]
 [0.56907898 0.88644344 0.61807784 0.85971709 0.12378685 0.08183459
  0.19446504 0.49671121 0.31565316]]

Minimum value: 0.0030441118945992

#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [16]:
import numpy as np

random_vector = np.random.rand(20)
mean_value = random_vector.mean()

print("Random vector of size 20:")
print(random_vector)
print(f"\nMean value: {mean_value}")

Random vector of size 20:
[0.71275256 0.60333727 0.18032395 0.1346339  0.86802877 0.28986086
 0.33672209 0.3719908  0.28356026 0.54914173 0.41143841 0.30280827
 0.8365806  0.01494684 0.920721   0.88291374 0.67675706 0.37670965
 0.03043072 0.22480136]

Mean value: 0.45042299248803797


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [17]:
import numpy as np

n, m = 6, 6

arr = np.zeros((n, m), dtype=int)

arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [18]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("Original array:\n", arr)
print("\nArray with zero border:\n", padded_arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with zero border:
 [[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [19]:
import numpy as np

print("0 * np.nan =", 0 * np.nan)
print("np.nan == np.nan =", np.nan == np.nan)
print("np.inf > np.nan =", np.inf > np.nan)
print("np.nan - np.nan =", np.nan - np.nan)
print("np.nan in set([np.nan]) =", np.nan in set([np.nan]))
print("0.7 == 7 * 0.1 =", 0.7 == 7 * 0.1)

0 * np.nan = nan
np.nan == np.nan = False
np.inf > np.nan = False
np.nan - np.nan = nan
np.nan in set([np.nan]) = True
0.7 == 7 * 0.1 = False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [20]:
import numpy as np

values = np.array([1, 2, 3, 4])

matrix = np.zeros((6, 6), dtype=int)

matrix[np.arange(1, 5), np.arange(0, 4)] = values

print(matrix)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 0 0]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [21]:
import numpy as np

checkerboard = np.zeros((6, 6), dtype=int)

checkerboard[1::2, 0::2] = 1
checkerboard[0::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [22]:
import numpy as np

shape = (8, 9, 10)
idx = 100

x = (idx // (shape[1] * shape[2])) % shape[0]
y = (idx // shape[2]) % shape[1]
z = idx % shape[2]

print(f"Index of the 100th element is: ({x}, {y}, {z})")

Index of the 100th element is: (1, 1, 0)


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [23]:
import numpy as np

matrix = np.random.rand(6, 6)

min_val = matrix.min()
max_val = matrix.max()

normalized_matrix = (matrix - min_val) / (max_val - min_val)

print("Original matrix:\n", matrix)
print("\nNormalized matrix:\n", normalized_matrix)

Original matrix:
 [[0.37887113 0.93719396 0.5756652  0.10703441 0.27867202 0.26588528]
 [0.94379847 0.06356755 0.81159246 0.80021369 0.53582037 0.00198848]
 [0.62254317 0.59099906 0.38486602 0.88567705 0.89652956 0.43104259]
 [0.7468797  0.29376371 0.83809784 0.41680184 0.46529792 0.16407632]
 [0.81869056 0.53385653 0.59871793 0.57532043 0.79165522 0.15497684]
 [0.86653306 0.90790574 0.58361896 0.44473852 0.59229525 0.16070213]]

Normalized matrix:
 [[0.40016846 0.99298742 0.6091215  0.11153622 0.29377851 0.28020173]
 [1.         0.06538374 0.8596256  0.84754379 0.56681485 0.        ]
 [0.65889585 0.62540276 0.40653373 0.93828753 0.94981056 0.45556335]
 [0.79091454 0.30980265 0.88776862 0.44044272 0.49193514 0.17210248]
 [0.86716226 0.56472967 0.63359855 0.60875543 0.83845653 0.16244079]
 [0.91796072 0.96188962 0.61756668 0.47010547 0.62677905 0.16851981]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [24]:
import numpy as np

arr = np.random.rand(4, 5)  # 4x5 مصفوفة

num_elements = arr.size

item_size = arr.itemsize
total_bytes = arr.nbytes

print(f"Number of elements: {num_elements}")
print(f"Length of one element in bytes: {item_size}")
print(f"Total bytes consumed by the elements: {total_bytes}")

Number of elements: 20
Length of one element in bytes: 8
Total bytes consumed by the elements: 160


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [25]:
import numpy as np

A = np.random.rand(6, 3)

B = np.random.rand(3, 4)

C = np.dot(A, B)

print("Matrix A (6x3):\n", A)
print("\nMatrix B (3x4):\n", B)
print("\nProduct matrix C (6x4):\n", C)

Matrix A (6x3):
 [[0.06991394 0.49238223 0.10995836]
 [0.15917692 0.23188276 0.7407614 ]
 [0.70082744 0.1151295  0.07652755]
 [0.61851951 0.80284585 0.02765748]
 [0.27895091 0.37137873 0.73438033]
 [0.97439055 0.70037269 0.07292467]]

Matrix B (3x4):
 [[0.42939232 0.26237374 0.53725292 0.39931024]
 [0.5969092  0.16110246 0.88563703 0.37394936]
 [0.69981686 0.93741681 0.52547827 0.93787825]]

Product matrix C (6x4):
 [[0.40087871 0.20074439 0.53141414 0.31517093]
 [0.72515961 0.77352292 0.68013624 0.84501738]
 [0.42320705 0.27416458 0.51869811 0.3946737 ]
 [0.76416878 0.31755031 1.05786483 0.57314422]
 [0.8553905  0.8214399  0.86467486 0.93902414]
 [0.88748864 0.43684707 1.18209049 0.7193825 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [26]:
import numpy as np

arr = np.array([1, 4, 6, 2, 9, 3, 8, 10, 7])

mask = (arr >= 3) & (arr <= 8)
arr[mask] = -arr[mask]

print(arr)

[ 1 -4 -6  2  9 -3 -8 10 -7]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5), -1))

from numpy import *

print(sum(range(5), -1))

9
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [28]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])

print("a > b\n")
print(a > b)

print("\na >= b\n")
print(a >= b)

print("\na < b\n")
print(a < b)

print("\na <= b\n")
print(a <= b)

a > b

[False False]

a >= b

[False False]

a < b

[ True  True]

a <= b

[ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [29]:
import numpy as np

print("np.array(0) / np.array(0):")
print(np.array(0) / np.array(0))

print("\nnp.array(0) // np.array(0):")
try:
    print(np.array(0) // np.array(0))
except Exception as e:
    print("Error:", e)

print("\nnp.array([np.nan]).astype(int).astype(float):")
try:
    result = np.array([np.nan]).astype(int).astype(float)
    print(result)
except Exception as e:
    print("Error:", e)

np.array(0) / np.array(0):
nan

np.array(0) // np.array(0):
0

np.array([np.nan]).astype(int).astype(float):
[-9.22337204e+18]


/tmp/ipython-input-2719379127.py:4: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-2719379127.py:8: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-2719379127.py:14: RuntimeWarning: invalid value encountered in cast
  result = np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [30]:
import numpy as np

def round_away_from_zero(arr):
    return np.where(arr > 0, np.ceil(arr), np.floor(arr))

arr = np.array([1.2, -1.2, 3.7, -3.7, 0.0])

rounded = round_away_from_zero(arr)
print("Original:", arr)
print("Rounded away from zero:", rounded)

Original: [ 1.2 -1.2  3.7 -3.7  0. ]
Rounded away from zero: [ 2. -2.  4. -4.  0.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [31]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(a, b)
print("Common values:", common_values)

Common values: [3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`